---
- name: install packages
  yum:
    name:
      - httpie
      - haproxy
    state: latest
- name: configure haproxy
  template:
    src: ./haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: start haproxy
